package net.sodacan.rules;
import net.sodacan.rules.Event;
import net.sodacan.rules.State;
import net.sodacan.rules.Sender;

rule "initialize show"	
  then
  	insert(new State("eaves", "off"));
end

rule "Default eaves show"
  when
		Tick(daytime==true)
		not Proposal(name=="eaves",priority>1)
  then
  	insertLogical(new Proposal("eaves",0, "off"));
end

rule "Is it night light show"
	when
		Tick(nighttime==true)
		not Proposal(name=="eaves",priority>2)
	then
		insertLogical(new Proposal("eaves",2,"nightlight"));
end

rule "Is it christmas"
	when
		Tick(nighttime==true,month==12)
		not Proposal(name=="eaves",priority>3)
	then
		insertLogical(new Proposal("eaves",3,"christmas"));
end

rule "Send show"
	when
		Proposal($sn: name, $n: show)
		$s: State(name==$sn)
	then
		$s.setValue($n);
		update($s);
		System.out.println("****eaves show is: " + $n );
end