package net.sodacan.rules;
import net.sodacan.rules.Event;
import net.sodacan.rules.State;
import net.sodacan.rules.Sender;
import net.sodacan.rules.DayNight;

rule "initialize show"	
  then
  	insert(new State("show", "off"));
end

rule "Default show"
  when
		DayNight(value=="day")
		not Proposal(name=="show",priority>1)
  then
  	insert(new Proposal("show",0, "off"));
end

rule "Is it night light show"
	when
		DayNight(value=="night")
		not Proposal(name=="show",priority>2)
	then
		insertLogical(new Proposal("show",2,"nightlight"));
end

rule "Is it christmas"
	when
		DayNight(value=="night")
		Month(value==12)
		not Proposal(name=="show",priority>3)
	then
		insertLogical(new Proposal("show",3,"christmas"));
end

rule "Send show"
	when
		Proposal(name=="show", $n: show)
		$s: State(name=="show")
	then
		$s.setValue($n);
		update($s);
		System.out.println("****Show is: " + $n );
end